"""added chip table and added foreignkey in user table

Revision ID: 36ad83cd0534
Revises: 38e46ccdd47f
Create Date: 2023-10-19 20:04:16.826685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36ad83cd0534'
down_revision: Union[str, None] = '38e46ccdd47f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chip',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=8), nullable=False),
    sa.Column('sn', sa.Integer(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.add_column('user', sa.Column('chip_id', sa.UUID(), nullable=True))
    op.drop_constraint('user_rfid_token_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['chip_id'])
    op.create_foreign_key(None, 'user', 'chip', ['chip_id'], ['id'])
    op.drop_column('user', 'rfid_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('rfid_token', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_rfid_token_key', 'user', ['rfid_token'])
    op.drop_column('user', 'chip_id')
    op.drop_table('chip')
    # ### end Alembic commands ###
