"""removed action column in log table

Revision ID: 38e46ccdd47f
Revises: 1a4047747b4d
Create Date: 2023-10-15 00:17:18.685806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38e46ccdd47f'
down_revision: Union[str, None] = '1a4047747b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log', 'action')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('action', postgresql.ENUM('login', 'logout', name='actiontype'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
