"""removed timestamp column and added start_timestamp and end_timestamp in user table

Revision ID: 3bffeec18d54
Revises: f6fe30572506
Create Date: 2023-10-15 00:06:37.485730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3bffeec18d54'
down_revision: Union[str, None] = 'f6fe30572506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('start_timestamp', sa.DateTime(), nullable=False))
    op.add_column('log', sa.Column('end_timestamp', sa.DateTime(), nullable=False))
    op.drop_column('log', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('log', 'end_timestamp')
    op.drop_column('log', 'start_timestamp')
    # ### end Alembic commands ###
