"""added userid in token table and removed chipid in user table

Revision ID: 87427d476a45
Revises: 59eb1f713b82
Create Date: 2023-10-19 21:41:04.985285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87427d476a45'
down_revision: Union[str, None] = '59eb1f713b82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chip', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'chip', ['user_id'])
    op.create_foreign_key(None, 'chip', 'user', ['user_id'], ['id'])
    op.drop_constraint('user_chip_id_key', 'user', type_='unique')
    op.drop_constraint('user_chip_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'chip_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('chip_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_chip_id_fkey', 'user', 'chip', ['chip_id'], ['id'])
    op.create_unique_constraint('user_chip_id_key', 'user', ['chip_id'])
    op.drop_constraint(None, 'chip', type_='foreignkey')
    op.drop_constraint(None, 'chip', type_='unique')
    op.drop_column('chip', 'user_id')
    # ### end Alembic commands ###
